name: Test, lint and publish image

on:
  push:
    branches:
      - master

jobs:
  testy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - name: Stahni kod
        uses: actions/checkout@v3

      - name: Nastav Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Instaluj zavislosti
        run: pip install -r requirements.txt

      - name: Spust testy
        run: pytest

      - name: Spust kontrolu kodu
        run: flake8 src/

      - name: Kontrola
        run: echo "Něco se pokazilo"
        if: failure()

  build-and-push:
    runs-on: ubuntu-latest
    needs: testy
    steps:
    - name: Stahni kod
      uses: actions/checkout@v3

    - name: login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: hovnoprdelstetky/god-not-responding:latest