name: muj prvni workflow

on:
  push:
    branches:
      - master

jobs:
  testy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - name: Stahni kod
        uses: actions/checkout@v3

      - name: Nastav Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Instaluj zavislosti
        run: pip install -r requirements.txt

      - name: Spust testy
        run: pytest

      - name: Spust kontrolu kodu
        run: flake8 src/

      - name: kontrola
        run: echo "Něco se pokazilo"
        if: failure()
  